# Generated by Django 4.2.11 on 2024-05-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
